### ISSUE TITLE
New Shortcode to add a Row with custom sharing Buttons

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#144]
Add a new shortcode (configurable via form entries like the Donation Form) to add a row of Sharing Buttons. 
Currently the sharing Buttons are located to the left of the page and default to the actual page. This could help to easily optimize petition workflows.

Common petition workflows work as follows:

1. Form is presented below petition text (and evtl. progress bar) - filled out and submitted by user
2. Success message is displayed inline with step 2: spread the word and share this petition - usually one can click on one or more social media buttons/icons presented in a row below the motivational text
3. below a donation form is presented as third step to support the cause

the proposed shortcode would fill in the gap to easily realize Step 2 of the above workflow.

The short code would ask for

- URL to be shared*
- Text for Twitter (has to be urlencoded)
- Text for WhatsApp and Telegram Message (has to be urlencoded)
- Text for Emailsubject* (has to be urlencoded)
- Text for Emailbody (has to be urlencoded)

The Sharing buttons presented in a Row would be
Twitter - Facebook - Whatsapp - Telegram - Mail

- When sharing on Twitter, Whatsapp/Telegram, the url to be shared would be prepended with the eventually added Texts for the respective platform. When sharing via Email, the Emailbody would be appended by the url to be shared.

**Q: How should the sharing links look like?**
https://www.sharelinkgenerator.com/ gives information about the links for twitter, Facebook and Email. 
Whatsapp-Links and Telegram links look as follows: 
`https://wa.me/send?text=<URLENCODED TEXT AND URL>`
`https://telegram.me/share/url?url=<URLENCODED URL>&text=<URLENCODED TEXT>`

**Q: WHY should this be implemented as Shortcode (with the possibility to configure the shortcode easily with a click of a button in the html editor (like the donation form) - and not as a ACF "Inhaltsblock"?**
A: Only an implementation as shortcode allows for integration of the Sharing Button row directly in the form confirmation message, so that one has the option to show the sharing button row only to visitors that have filled out the form - in the confirmation message of the form.

**Comment by cyrillbolliger** [comment]
Thanks a lot for the suggestion.

Implementing this as shortcode with a generator is going to be really messy and doesn't fit well into the concept of the theme. What's the argument against redirecting the user to a dedicated thank you page after form submission?
![image](https://user-images.githubusercontent.com/12530490/153463853-ddb91f8f-8ea0-4bf6-8015-3d53a522866d.png)

If using the dedicated thank you page instead of the quick and dirty inline message, the share buttons could be integrated as ACF content block, which is ways cleaner and achieved faster. It would also be simpler to manage, especially for inexperienced publishers.

Would this be a viable solution?

**Comment by politbuero-kampagnen** [comment]
I definitely think this could be a viable solution for the form submission scenario!
